# Generated by Django 3.2.4 on 2021-06-15 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecom', '0003_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('confirmed', 'Confirmed'), ('Delivered', 'Delivered')], default='Pending', max_length=50)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.customer')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.portfoliopricing')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.portfoliotheme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
